"""API Package"""
from app.api.auth import router as auth_router
from app.api.users import router as users_router
from app.api.patients import router as patients_router
from app.api.hospitals import router as hospitals_router
from app.api.health_records import router as health_records_router
from app.api.blood_samples import router as blood_samples_router
from app.api.smartwatch import router as smartwatch_router
from app.api.cancer_detection import router as cancer_detection_router
from app.api.admin import router as admin_router
from app.api.appointments import router as appointments_router
from app.api.notifications import router as notifications_router
from app.api.reports import router as reports_router
from app.api.analytics import router as analytics_router
from app.api.blood_donor import router as blood_donor_router
from app.api.clinical_decision import router as clinical_decision_router
from app.api.genomics import router as genomics_router
from app.api.research import router as research_router
from app.api.population_health import router as population_health_router
from app.api.patient_engagement import router as patient_engagement_router
from app.api.communication import router as communication_router
from app.api.billing_enhanced import router as billing_enhanced_router
from app.api.quality_safety import router as quality_safety_router
from app.api.supply_chain import router as supply_chain_router
from app.api.telehealth import router as telehealth_router
from app.api.pathology import router as pathology_router
from app.api.rehabilitation import router as rehabilitation_router
from app.api.nutrition_enhanced import router as nutrition_enhanced_router
from app.api.mental_health_enhanced import router as mental_health_enhanced_router
from app.api.clinical_trials_v2 import router as clinical_trials_v2_router
from app.api.radiology_enhanced import router as radiology_enhanced_router
from app.api.pharmacy_enhanced import router as pharmacy_enhanced_router
from app.api.education import router as education_router
from app.api.social_determinants import router as social_determinants_router
from app.api.wearable_enhanced import router as wearable_enhanced_router
from app.api.emergency import router as emergency_router
from app.api.workforce import router as workforce_router
from app.api.documents import router as documents_router
